janunde/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.views.defaults import page_not_found, server_error
from django.views.generic.base import RedirectView, TemplateView

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from wagtail.contrib.sitemaps.views import sitemap
from wagtail.images.views.serve import ServeView

from core.views import search


urlpatterns = [
    url(r"^404/$", page_not_found, kwargs={"exception": Exception("Page not Found")}),
    url(r"^500/$", server_error),
    url(r"^admin/", include(wagtailadmin_urls)),
    url(r"^documents/", include(wagtaildocs_urls)),
    url(
        r"^images/([^/]*)/(\d*)/([^/]*)/[^/]*$",
        ServeView.as_view(action="redirect"),
        name="wagtailimages_serve",
    ),
    url(r"^sitemap\.xml$", sitemap, name="sitemap"),
    url(
        r"^robots\.txt$",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    url(r"^search/", search, name="search",),
    url(
        r"^lueneburg/(?P<path>.*)",
        RedirectView.as_view(url="/netzwerk-projekte/janun-lüneburg/%(path)s"),
    ),
    url(
        r"^weltbewusst-lg",
        RedirectView.as_view(
            url="/netzwerk-projekte/janun-lüneburg/weltbewusst-lüneburg-neu/"
        ),
    ),
    url(
        r"^scp",
        RedirectView.as_view(
            url="/netzwerk-projekte/janun-landesbüro/silent-climate-parade/"
        ),
    ),
    url(
        r"^herbstspektakel",
        RedirectView.as_view(
            url="/netzwerk-projekte/janun-landesbüro/herbstspektakel/"
        ),
    ),
    url(
        r"^imagine", RedirectView.as_view(url="/veranstaltungen/herbstspektakel-2017/")
    ),
    url(r"^stadttraum", RedirectView.as_view(url="/veranstaltungen/stadttraum/")),
    url(
        r"^veranstaltungen/herbstspektakel-2018",
        RedirectView.as_view(url="/veranstaltungen/stadttraum/"),
    ),
    url(
        r"^netzwerk-projekte/janun-landesbuero/(?P<path>.*)",
        RedirectView.as_view(url="/netzwerk-projekte/janun-landesbüro/%(path)s"),
    ),
    url(
        r"^netzwerk-projekte/janun-landesb%FCro/(?P<path>.*)",
        RedirectView.as_view(url="/netzwerk-projekte/janun-landesbüro/%(path)s"),
    ),
    url(r"^festival", RedirectView.as_view(url="/veranstaltungen/janun-festival/")),
    url(r"^webinare", RedirectView.as_view(url="/veranstaltungen/?typ=Online")),
]


if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r"^__debug__/", include(debug_toolbar.urls)),
    ]


urlpatterns += [url(r"", include(wagtail_urls))]

jobs/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator
from django import forms

from wagtail.admin.edit_handlers import (
    FieldPanel,
    StreamFieldPanel,
    MultiFieldPanel,
    HelpPanel,
)
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.core.fields import StreamField
from wagtail.search import index

from core.blocks import StandardStreamBlock
from core.models import BasePage, StandardPage

from .fields import ChoiceArrayField


class JobOfferIndexPage(BasePage):
    subpage_types = ["JobOfferPage"]
    max_count_per_parent = 1

    heading = models.CharField("Überschrift", max_length=255, blank=True)
    highlight_in_heading = models.CharField(
        "Hervorhebungen in der Überschrift",
        help_text="Wiederhole Text aus der Überschrift der farblich hervorgehoben werden soll",
        blank=True,
        max_length=255,
    )
    subtitle = models.CharField("Untertitel", max_length=255, blank=True)

    before_jobs = StreamField(
        StandardStreamBlock,
        blank=True,
        verbose_name="Intro-Text (wenn Jobs vorhanden)",
        help_text="Wird als Text vor der Liste der Stellenanzeigen angezeigt. Aber nur wenn es auch Stellenanzeigen gibt.",
    )

    after_jobs = StreamField(
        StandardStreamBlock,
        blank=True,
        verbose_name="Outro-Text (wenn Jobs vorhanden)",
        help_text="Wird als Text nach der Liste der Stellenanzeigen angezeigt. Aber nur wenn es auch Stellenanzeigen gibt.",
    )

    empty = StreamField(
        StandardStreamBlock(),
        blank=True,
        null=True,
        verbose_name="Wenn keine Jobs",
        help_text="Wird angezeigt, wenn es keine Stellenanzeigen gibt.",
    )

    def get_context(self, request):
        context = super().get_context(request)
        context["jobs"] = JobOfferPage.objects.all().live()
        return context

    search_fields = BasePage.search_fields + [
        index.SearchField("heading"),
        index.SearchField("subtitle"),
        index.SearchField("before_jobs"),
        index.SearchField("after_jobs"),
    ]

    content_panels = [
        MultiFieldPanel(
            [
                FieldPanel("title"),
                FieldPanel("heading"),
                FieldPanel("highlight_in_heading"),
                FieldPanel("subtitle"),
            ],
            "Kopf",
        ),
        StreamFieldPanel("before_jobs"),
        HelpPanel(
            template="jobs/admin_add_job_button.html",
            heading="Stellenauschreibung erstellen",
        ),
        StreamFieldPanel("after_jobs"),
        StreamFieldPanel("empty"),
    ]

    class Meta:
        verbose_name = "Auflistung von Stellenausschreibungen"
        verbose_name_plural = "Auflistungen von Stellenausschreibungen"


class JobOfferPage(StandardPage):
    parent_page_types = ["JobOfferIndexPage"]
    subpage_types = ["core.StandardPage"]

    valid_through = models.DateTimeField(
        "Bewerbungsfrist",
        blank=True,
        null=True,
        validators=[
            MinValueValidator(timezone.now, message="Sollte in der Zukunft liegen")
        ],
    )
    job_title = models.CharField("Job-Titel", max_length=255)
    job_location = models.CharField(
        "Job-Ort", max_length=255, blank=True, default="Hannover"
    )
    hiring_organization_name = models.CharField(
        "Arbeitgeber", max_length=255, default="JANUN e.V."
    )
    hiring_organization_url = models.URLField(
        "Website des Arbeitgebers", blank=True, default="https://www.janun.de/"
    )
    EMPLOYMENT_TYPE_CHOICES = [
        ("FULL_TIME", "Vollzeit"),
        ("PART_TIME", "Teilzeit"),
        ("CONTRACTOR", "Auftragnehmer"),
        ("TEMPORARY", "befristet"),
        ("INTERN", "Praktikum"),
        ("VOLUNTEER", "Freiwilligendienst"),
        ("PER_DIEM", "tageweise"),
        ("OTHER", "anderes"),
    ]
    employment_type = ChoiceArrayField(
        models.CharField(max_length=20, choices=EMPLOYMENT_TYPE_CHOICES),
        verbose_name="Art der Anstellung",
        blank=True,
        null=True,
    )
    base_salary_amount = models.DecimalField(
        "Grundgehalt", blank=True, null=True, decimal_places=2, max_digits=10
    )
    BASE_SALARY_UNIT_CHOICES = [
        ("HOUR", "pro Stunde"),
        ("DAY", "pro Tag"),
        ("WEEK", "pro Woche"),
        ("MONTH", "pro Monat"),
        ("YEAR", "pro Jahr"),
    ]
    base_salary_unit = models.CharField(
        "Zeitraum für Grundgehalt",
        max_length=10,
        default="MONTH",
        choices=BASE_SALARY_UNIT_CHOICES,
    )
    auto_unpublish = models.BooleanField(
        "Automatisch depublizieren",
        help_text="Depubliziert die Seite automatisch nach der Bewerbungsfrist",
        default=True,
    )

    def get_employment_type_display(self) -> [str]:
        result = []
        for employment_type in self.employment_type:
            for choice in self.EMPLOYMENT_TYPE_CHOICES:
                if employment_type == choice[0]:
                    result.append(choice[1])
        return result

    @property
    def structured_data(self):
        return {
            "@type": "JobPosting",
            "title": self.job_title,
            "description": str(self.body),
            "datePosted": self.first_published_at,
            "validThrough": self.valid_through,
            "hiringOrganization": {
                "@type": "Organization",
                "name": self.hiring_organization_name,
                "sameAs": self.hiring_organization_url,
            },
            "jobLocation": {"@type": "Place", "address": self.job_location},
            "employmentType": self.employment_type,
            "baseSalary": {
                "@type": "MonetaryAmount",
                "currency": "EUR",
                "value": {
                    "@type": "QuantitativeValue",
                    "value": self.base_salary_amount,
                    "unitText": self.base_salary_unit,
                },
            },
        }

    def save(self, *args, **kwargs):
        if self.valid_through and self.auto_unpublish:
            self.expire_at = self.valid_through
        super().save(*args, **kwargs)

    content_panels = [
        FieldPanel("title"),
        FieldPanel("subtitle"),
        ImageChooserPanel("feed_image"),
        MultiFieldPanel(
            [
                HelpPanel(
                    "<p>Sorgt für eine bessere Platzierung als Jobanzeige bei Google und co.</p>"
                ),
                FieldPanel("job_title"),
                FieldPanel("job_location"),
                FieldPanel("hiring_organization_name"),
                FieldPanel("hiring_organization_url"),
                FieldPanel("valid_through"),
                FieldPanel("auto_unpublish"),
                FieldPanel("employment_type", widget=forms.CheckboxSelectMultiple),
                FieldPanel("base_salary_amount"),
                FieldPanel("base_salary_unit"),
            ],
            heading="Infos",
        ),
        StreamFieldPanel("body"),
    ]

    class Meta:
        verbose_name = "Stellenausschreibung"
        verbose_name_plural = "Stellenausschreibungen"

jobs/templates/jobs/_job.html
{% load wagtailcore_tags wagtailimages_tags %}

<a class="mb-8 md:mb-12 md:h-36 group overflow-hidden flex bg-white shadow md:shadow-md transition-shadow duration-200 hover:shadow-lg text-gray-700 rounded-md" href="{% pageurl job %}">  
  <div class="p-4 md:p-5 overflow-hidden flex flex-col">

    <h3 class="text-gray-900 text-base md:text-lg xl:text-xl mb-1 font-semibold group-hover:text-green-500 hyphens-auto">{{ job.title }}</h3>
    {% if job.subtitle %}
      <div class="text-xs md:text-sm hyphens-auto" title="{{ job.subtitle }}">{{ job.subtitle|truncatechars:120 }}</div>
    {% endif %}

    <div class="mt-4 text-xs md:text-sm -mx-1">
      {% comment %} {% if job.hiring_organization_name %}<span class="mx-1 whitespace-nowrap">Bei {{ job.hiring_organization_name }}</span>{% endif %}
      {% if job.job_location %}<span class="mx-1 whitespace-nowrap">in {{ job.job_location }}</span>{% endif %}
      <span class="mx-1 whitespace-nowrap">{{ job.get_employment_type_display|join:", " }}</span>
      {% if job.base_salary_amount %}<span class="mx-1 whitespace-nowrap">{{ job.base_salary_amount }} {{ job.get_base_salary_unit_display }}</span>{% endif %} {% endcomment %}
      {% if job.valid_through %}<div class="mx-1 mt-1 whitespace-nowrap">Bewerbungsfrist: {{ job.valid_through }}</div>{% endif %}
    </div>

  </div>
</a>

jobs/templates/jobs/admin_add_job_button.html
<fieldset>
    {% if self.heading %}
        <legend>{{ self.heading }}</legend>
    {% endif %}
    <div class="{{ self.classname }}">
        <p>Stellenauschreibungen müssen als Unterseiten dieser Seite erstellt werden.</p>
        {% if self.instance.pk %}
            <a href="{% url 'wagtailadmin_pages:add_subpage' self.instance.pk %}" class="button bicolor icon icon-plus">Stellenauschreibung erstellen</a>
        {% endif %}
    </div>
</fieldset>

jobs/templates/jobs/job_offer_index_page.html
{% extends "core/__base.html" %}
{% load wagtailcore_tags stuff %}

{% block body_class %}{% endblock %}

{% block content %}
<main class="max-w-3xl mx-auto px-4">

  {% include "core/_breadcrumbs.html" %}

  <header class="mb-10 md:mb-16">
    <h1 class="leading-tighter text-green-500 hyphens-auto text-3xl md:text-4xl font-bold mt-0 mb-2">
      {% if self.heading %}
        {% highlight self.heading self.highlight_in_heading "text-purple" %}
      {% else %}
        {{ self.title }}
      {% endif %}
    </h1>
    {% if self.subtitle %}
      <h2 class="leading-tight md:leading-snug text-gray-700 text-lg md:text-xl my-0">{{ self.subtitle }}</h2>
    {% endif %}
  </header>

  <div class="max-w-3xl mx-auto userim">
    {% if jobs %}
      {% include_block self.before_jobs %}
      <div>
        {% for job in jobs %}
          {% include "./_job.html" %}
        {% endfor %}
      </div>
      {% include_block self.after_jobs %}
    {% else %}
      {% include_block self.empty %}
    {% endif %}


  </div>
   
</main>
{% endblock %}

jobs/templates/jobs/job_offer_page.html
{% extends "core/__base.html" %}
{% load wagtailcore_tags stuff %}

{% block body_class %}{% endblock %}

{% block content %}
<main class="max-w-3xl mx-auto px-4">

  {% include "core/_breadcrumbs.html" %}

  <header class="mb-10">
    <h1 class="leading-tighter hyphens-auto text-green-500 text-3xl md:text-4xl font-bold mt-0 mb-2">{{ self.title }}</h1>
    {% if self.subtitle %}
      <h2 class="leading-tight md:leading-snug text-gray-700 text-lg md:text-xl my-0">{{ self.subtitle }}</h2>
    {% endif %}
  </header>

  <div class="max-w-3xl mx-auto userim">
    {% include_block self.body %}
  </div>

  {% render_json_ld self.structured_data %}
   
</main>
{% endblock %}